name = "xontol"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "188.166.183.136:443"
UUID = "f96fa46a-4042-4c50-ba3c-de92add0ee5b"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
